#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=dream_sapphire

ZIP=$(cd $(dirname $1) ; pwd -P; )/$(basename $1)

mkdir -p ../../../vendor/htc/$DEVICE/proprietary
cd ../../../vendor/htc/$DEVICE/proprietary

unzip -j $ZIP system/bin/akmd
unzip -j $ZIP system/etc/AudioFilter.csv
unzip -j $ZIP system/etc/AudioPara4.csv
unzip -j $ZIP system/etc/AudioPreProcess.csv
unzip -j $ZIP system/etc/firmware/brf6300.bin
unzip -j $ZIP system/etc/wifi/Fw1251r1c.bin
unzip -j $ZIP system/lib/egl/libGLES_qcom.so
unzip -j $ZIP system/lib/libaudioeq.so
unzip -j $ZIP system/lib/libgps.so
unzip -j $ZIP system/lib/libhtc_acoustic.so
unzip -j $ZIP system/lib/libhtc_ril.so
unzip -j $ZIP system/lib/liblvmxipc.so
unzip -j $ZIP system/lib/libmm-adspsvc.so
unzip -j $ZIP system/lib/liboemcamera.so
unzip -j $ZIP system/lib/libOmxH264Dec.so
unzip -j $ZIP system/lib/libOmxMpeg4Dec.so
unzip -j $ZIP system/lib/libOmxVidEnc.so
unzip -j $ZIP system/lib/libomx_wmadec_sharedlibrary.so
unzip -j $ZIP system/lib/libomx_wmvdec_sharedlibrary.so
unzip -j $ZIP system/lib/libpvasfcommon.so
unzip -j $ZIP system/lib/libpvasflocalpbreg.so
unzip -j $ZIP system/lib/libpvasflocalpb.so
unzip -j $ZIP system/etc/pvasflocal.cfg

cd -

chmod 755 ../../../vendor/htc/$DEVICE/proprietary/akmd
(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/htc/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \\
    vendor/htc/__DEVICE__/proprietary/libgps.so:obj/lib/libgps.so

# All the blobs necessary for sapphire
PRODUCT_COPY_FILES += \\
    vendor/htc/__DEVICE__/proprietary/akmd:system/bin/akmd \\
    vendor/htc/__DEVICE__/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \\
    vendor/htc/__DEVICE__/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \\
    vendor/htc/__DEVICE__/proprietary/brf6300.bin:system/etc/firmware/brf6300.bin \\
    vendor/htc/__DEVICE__/proprietary/Fw1251r1c.bin:system/etc/wifi/Fw1251r1c.bin \\
    vendor/htc/__DEVICE__/proprietary/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \\
    vendor/htc/__DEVICE__/proprietary/libaudioeq.so:system/lib/libaudioeq.so \\
    vendor/htc/__DEVICE__/proprietary/libgps.so:system/lib/libgps.so \\
    vendor/htc/__DEVICE__/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \\
    vendor/htc/__DEVICE__/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \\
    vendor/htc/__DEVICE__/proprietary/liblvmxipc.so:system/lib/liblvmxipc.so \\
    vendor/htc/__DEVICE__/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \\
    vendor/htc/__DEVICE__/proprietary/liboemcamera.so:system/lib/liboemcamera.so \\
    vendor/htc/__DEVICE__/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \\
    vendor/htc/__DEVICE__/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \\
    vendor/htc/__DEVICE__/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so

ifndef WITH_DS_HTCACOUSTIC_HACK
PRODUCT_COPY_FILES += \\
    vendor/htc/__DEVICE__/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv
endif

ifdef WITH_WINDOWS_MEDIA
PRODUCT_COPY_FILES += \\
    vendor/htc/__DEVICE__/proprietary/libomx_wmadec_sharedlibrary.so:system/lib/libomx_wmadec_sharedlibrary.so \\
    vendor/htc/__DEVICE__/proprietary/libomx_wmvdec_sharedlibrary.so:system/lib/libomx_wmvdec_sharedlibrary.so \\
    vendor/htc/__DEVICE__/proprietary/libpvasfcommon.so:system/lib/libpvasfcommon.so \\
    vendor/htc/__DEVICE__/proprietary/libpvasflocalpbreg.so:system/lib/libpvasflocalpbreg.so \\
    vendor/htc/__DEVICE__/proprietary/libpvasflocalpb.so:system/lib/libpvasflocalpb.so \\
    vendor/htc/__DEVICE__/proprietary/pvasflocal.cfg:system/etc/pvasflocal.cfg
endif
EOF

./setup-makefiles.sh
